# Generated by Django 5.2 on 2025-05-01 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_jobs', '0001_initial'),
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected'), ('Selected', 'Selected')], default='Applied', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_jobs.job')),
                ('job_seeker', models.ForeignKey(limit_choices_to={'usertype': 'Job_Seeker'}, on_delete=django.db.models.deletion.CASCADE, to='app_users.user')),
            ],
            options={
                'verbose_name_plural': 'Job Applications',
                'ordering': ['-application_date'],
            },
        ),
    ]
