# Generated by Django 5.2 on 2025-05-01 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('date_of_birth', models.DateField()),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('higher_education_degree', models.CharField(max_length=100)),
                ('higher_education_branch', models.CharField(max_length=100)),
                ('higher_education_year_of_passout', models.IntegerField()),
                ('experience', models.PositiveIntegerField(help_text='Experience in years')),
                ('location', models.CharField(max_length=200)),
                ('zipcode', models.CharField(max_length=10)),
                ('usertype', models.CharField(choices=[('Job_Seeker', 'Job Seeker'), ('Recruiter', 'Recruiter'), ('Employee', 'Employee')], max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('company_address', models.TextField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
