# Generated by Django 5.2 on 2025-05-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='temp1234', max_length=128),
        ),
    ]
